### ISSUE TITLE
Fails to fix all instances

### ISSUE THREAD

**Issue by wolfadex** [lue-bird/elm-review-import-simple#1]
I haven't had a chance to make an SSCCE yet, but I can reliably reproduce by starting from this commit https://github.com/wolfadex/elm-rte-toolkit/commit/73e27f487210188478c51eb90330cb0383f86724 on my fork of elm-rte-toolkit, and then uncommenting `Review.ImportSimple.rule` in the ReviewConfig.

**Comment by lue-bird** [comment]
Funny bug. Fixed in the now published 1.0.3, applying fixes after your commit seems to produce compiling code now.

Thanks for reporting!
